import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildRegistry } from '../build/plugins/vite-plugin-bem-levels.js';

const ROOT = resolve(import.meta.dirname, '..');

const PLATFORM_LEVELS = {
    desktop: ['common.blocks', 'desktop.blocks'],
    touch: ['common.blocks', 'touch.blocks'],
};

function bemTokensFrom(source) {
    return source.match(/bem:[a-zA-Z_-]+/g) || [];
}

// Documented divergences of the generated entry from the frozen pre-S0
// baseline. The parity assertion exists to forbid *silent* drops (OQ-6);
// deliberate payload changes must be enumerated here with their slice.
// Additions are recorded per platform; S3's removals predate this ledger's
// per-platform form and stay in their original shape — slices from S1 on
// declare additions only (drops remain unamendable).
const S3_DIVERGENCE = {
    added: ['bem:loader'],
    removed: ['bem:loader_type_js', 'bem:loader_type_bundle'], // bc-ilml (D-16, Q7)
};

const SLICE_ADDITIONS = {
    // S1 (bc-4izq): the env capability module joins both payloads; the
    // ua__dom common base becomes visible on desktop (touch already had it
    // from its now-deleted platform fork). bem:ua itself is unchanged — it
    // moved from the platform forks to common.blocks, same module name.
    desktop: ['bem:env', 'bem:ua__dom'],
    touch: ['bem:env'],
};

function readIfExists(filePath) {
    if (!existsSync(filePath)) return null;
    return readFileSync(filePath, 'utf8');
}

describe('platform entry generation (payload parity)', function() {
    for (const [platform, levels] of Object.entries(PLATFORM_LEVELS)) {
        describe(`${platform}`, function() {
            const genPath = resolve(ROOT, `build/platforms/${platform}.gen.js`);
            const baselinePath = resolve(ROOT, `specs/pre-s0-platforms-${platform}.txt`);

            it('generated entry exists and is committed', function() {
                const gen = readIfExists(genPath);
                assert.ok(gen, `build/platforms/${platform}.gen.js must be committed`);
                assert.ok(gen.startsWith('// @generated by build/generate-platform-entries.mjs'),
                    'generated entry must carry the @generated header');
            });

            it('payload parity: generated bem: set equals the pre-S0 hand-list set (± documented slice deltas)', function() {
                const gen = readFileSync(genPath, 'utf8');
                const baseline = readFileSync(baselinePath, 'utf8');
                const genSet = [...new Set(bemTokensFrom(gen))].sort();
                const baselineSet = [...new Set(bemTokensFrom(baseline))]
                    .filter((token) => !S3_DIVERGENCE.removed.includes(token))
                    .concat(S3_DIVERGENCE.added, SLICE_ADDITIONS[platform])
                    .sort();
                assert.deepStrictEqual(genSet, baselineSet,
                    `generated ${platform} entry diverged from the pre-S0 baseline beyond the documented slice deltas`);
            });

            it('keyboard__codes survives generation (OQ-6: silent drop forbidden)', function() {
                const gen = readFileSync(genPath, 'utf8');
                assert.ok(gen.includes("import 'bem:keyboard__codes';"),
                    'keyboard__codes must survive platform entry generation verbatim');
            });

            it('generated entry matches the live scan registry (freshness)', function() {
                const registry = buildRegistry(levels, ROOT);
                const expected = [...registry.modules.keys()]
                    .filter((name) => registry.modules.get(name).length > 0)
                    .sort();
                const gen = readFileSync(genPath, 'utf8');
                const genImports = [...gen.matchAll(/^import 'bem:([^']+)';$/gm)]
                    .map((m) => m[1]);
                assert.deepStrictEqual(genImports, expected,
                    'committed entry is stale — run: node build/generate-platform-entries.mjs');
            });
        });
    }
});
